// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Encryptor is an autogenerated mock type for the Encryptor type
type Encryptor struct {
	mock.Mock
}

// Encrypt provides a mock function with given fields: rawData
func (_m *Encryptor) Encrypt(rawData string) (string, error) {
	ret := _m.Called(rawData)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(rawData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rawData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
